name: Build and GH-Page Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
